export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const SEARCH_TASK_BY_NAME = 'SEARCH_TASK_BY_NAME';
export const SET_TASKS_AFTER_SEARCH = 'SET_TASKS_AFTER_SEARCH';
